### ISSUE TITLE
Conclusion for 2020 and TODO for 2021

### ISSUE THREAD

**Issue by ZYHowell** [ZYHowell/MS108-2020#10]
This is a conclusion for MS108 project in 2020: 
We've made: 
1. a number of docs
2. some improvements of source code: 
    a) bug fix: support a UART-about read/write following a RAM-about read/write(see line 161, `riscv_top.v`)
    b) enhancement: expose the signal indicating 'io buffer full' from UART to CPU
    c) enhancement: reset signal for CPU when the program ends execution(see program_finish and d_program_finish in `hci.v`)
    by c), we can now run multiple programs without manually pressing the bottom of FPGA, so an OJ(a server connected with FPGA) is available. 
    d) a script to run all testcases
3. improvement of testbench: 
    a) fix bug of `pi.c`
    b) add `heart.c`, which is a stress test. 
4. an exploration for CSR instructions and registers required by machine mode

We leave for the next generation: 
1. Better docs. They require reorganizing. 
2. Fix bug in https://github.com/ACMClassCourses/MS108-2020/issues/9
3. a better use of `hci.v`: it actually supports debug mode but we do not know how
4. REAL understand of CSR instructions and riscv privileged architecture: actually we do not know how to run an OS to test whether one really supports the two. FreeRTOS is a good choice to be the target.

**Comment by ZYHowell** [comment]
minor bug: 
1. some testcases(e.g. bulgarian, magic) are not robust enough: they may work well on someone's CPU with rv-toolchain 10.2.0 but failed with rv-toolchain 8.3.0. 
2. `program_finish` signal is not robust enough, one part is in UART while the other is in HCI, and the latter one is not controlled by `io_buffer_full`. Consider that: a write to 0x30004 is sent to hci.v, but in the next cycle the CPU receives `io_buffer_full=1`, then it tries to resend the write to 0x30004. However, although the corresponding write to UART is failed(since fifo is full), hci still recognizes the 0x30004 is the signal of program finish and it resets the CPU. In the end, the UART does not receive the last char corresponding to 0x30004 because CPU is reset before resending.

**Comment by ZYHowell** [comment]
I notice that many students have bugs in handling rdy and it is hard to debug on FPGA. So I suggest adding rdy signal in testbench and turn it to 0 not only before rst=0, but during the running for a while.

**Comment by jlhsmall** [comment]
In vivadodemo, "Connect FPGA with computer" should be moved before "Modify .sh files"
